package com.metaldetector.detectorapp.detectorapp.firebase.event

object EventName {
    const val splash_open = "splash_open"
    const val language_fo_open = "language_fo_open"
    const val language_fo_save_click = "language_fo_save_click"
    const val permission_open = "permission_open"
    const val permission_allow_click = "permission_allow_click"
    const val permission_continue_click = "permission_continue_click"

    const val home_view = "home_view"
    const val home_click = "home_click"
    const val favorite_click = "favorite_click"
    const val setting_click = "setting_click"
    const val alam_click  = "alam_click"
    const val home_refresh_click = "home_refresh_click"
    const val home_calender_click = "home_calender_click"
    const val home_seemore_click = "home_seemore_click"
    const val home_search_click = "home_search_click"
    const val home_alarm_click  = "home_alarm_click"
    const val team_click  = "team_click"
    const val live_now_view  = "live_now_view"
    const val leagues_click  = "leagues_click"
    const val search_favorite_click  = "search_favorite_click"
    const val name_team_click  = "name_team_click"
    const val name_leagues_click  = "name_leagues_click"
    const val stats_click  = "stats_click"
    const val fixtures_click  = "fixtures_click"
    const val squad_click  = "squad_click"
    const val team_favorite_click  = "team_favorite_click"
    const val fixtures_leagues_click  = "fixtures_leagues_click"
    const val table_click  = "table_click"
    const val leagues_favorite_click  = "leagues_favorite_click"
    const val match_click  = "match_click"
    const val infor_click  = "infor_click"
    const val stats_match_click  = "stats_match_click"
    const val lineup_click  = "lineup_click"
    const val table_match_click  = "table_match_click"

    const val setting_view  = "setting_view"
    const val setting_lang_click  = "setting_lang_click"
    const val share_click = "share_click"
    const val rate_click = "rate_click"
    const val rate_show = "rate_show"
    const val rate_not_now = "rate_not_now"
    const val rate_submit = "rate_submit"
    const val policy_click = "policy_setting_click"

    const val button_set_alarm_view  = "button_set_alarm_view"
    const val alarm_save = "alarm_save"
    const val alarm_view = "alarm_view"
}